linters: # which linters to run
  enable-all: true
  disable:
    - golint     # deprecated, replaced by 'revive'
    - interfacer # deprecated
    - maligned   # deprecated, replaced by 'govet fieldalignement'
    - scopelint  # deprecated, replaced by 'exportloopref'
    - paralleltest # global env prevents parallelism

    # there isn't a good reason for disabling these, they just don't
    # pass at the moment.
    - cyclop
    - errname
    - funlen
    - gochecknoglobals
    - gocognit
    - lll
    - nestif
    - nlreturn
    - revive
    - stylecheck
    - tenv
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
linters-settings: # what settings to run those linters with
  goimports:
    # A comma-separated list
    local-prefixes: github.com/datawire
  gomnd:
    settings:
      mnd:
        ignored-numbers: 0,1,2,10,32,64
  lll:
    # Mimic .editorconfig
    line-length: 100
    tab-width: 8
