name: quality-assurance
on:
  - push
  - pull_request
jobs:
  check:
    strategy:
      matrix:
        go-version:
         - '~1.17.0'
         - '~1.19.0'
    name: "${{ github.event_name }} / check / Go ${{ matrix.go-version }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '${{ matrix.go-version }}'
      - run: make check
      - name: Report test coverage to coveralls.io
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make tools/bin/goveralls &&
          tools/bin/goveralls -coverprofile=envconfig.cov -service=github
  lint:
    name: "${{ github.event_name }} / lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.19.0'
      - run: make lint
  pass:
    name: "${{ github.event_name }} / pass"
    runs-on: ubuntu-latest
    needs:
      - check
      - lint
    steps:
      - name: No-Op
        if: ${{ false }}
        run: "echo Pass"
